CREATE TABLE IF NOT EXISTS `encoding_outcome` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `encoding_item_id` VARCHAR(255) NOT NULL,
    `attempt_number` INT UNSIGNED NOT NULL,
    `profile_id` VARCHAR(128) NOT NULL,
    `requested_at` DATETIME DEFAULT NULL,
    `queued_at` DATETIME DEFAULT NULL,
    `encoding_started_at` DATETIME DEFAULT NULL,
    `encoding_finished_at` DATETIME DEFAULT NULL,
    `active_encoding_ms` BIGINT UNSIGNED DEFAULT NULL,
    `paused_ms` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `wall_clock_ms` BIGINT UNSIGNED DEFAULT NULL,
    `source_duration_ms` BIGINT UNSIGNED DEFAULT NULL,
    `source_file_size_bytes` BIGINT UNSIGNED DEFAULT NULL,
    `source_width` INT UNSIGNED DEFAULT NULL,
    `source_height` INT UNSIGNED DEFAULT NULL,
    `source_frame_rate` DECIMAL(10,4) DEFAULT NULL,
    `source_bit_rate` BIGINT UNSIGNED DEFAULT NULL,
    `source_video_codec` VARCHAR(128) DEFAULT NULL,
    `source_audio_codec` VARCHAR(128) DEFAULT NULL,
    `source_container` VARCHAR(128) DEFAULT NULL,
    `source_probe_json` LONGTEXT DEFAULT NULL,
    `output_file_size_bytes` BIGINT UNSIGNED DEFAULT NULL,
    `output_duration_ms` BIGINT UNSIGNED DEFAULT NULL,
    `output_width` INT UNSIGNED DEFAULT NULL,
    `output_height` INT UNSIGNED DEFAULT NULL,
    `output_frame_rate` DECIMAL(10,4) DEFAULT NULL,
    `output_bit_rate` BIGINT UNSIGNED DEFAULT NULL,
    `output_video_codec` VARCHAR(128) DEFAULT NULL,
    `output_audio_codec` VARCHAR(128) DEFAULT NULL,
    `output_container` VARCHAR(128) DEFAULT NULL,
    `output_probe_json` LONGTEXT DEFAULT NULL,
    `size_delta_bytes` BIGINT DEFAULT NULL,
    `size_delta_percent` DECIMAL(9,4) DEFAULT NULL,
    `bitrate_delta_bps` BIGINT DEFAULT NULL,
    `bitrate_delta_percent` DECIMAL(9,4) DEFAULT NULL,
    `encoded_output_abs_path` TEXT DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_encoding_outcome_item_attempt` (`encoding_item_id`, `attempt_number`),
    KEY `idx_encoding_outcome_item` (`encoding_item_id`),
    KEY `idx_encoding_outcome_profile` (`profile_id`),
    KEY `idx_encoding_outcome_created_at` (`created_at`),
    CONSTRAINT `fk_encoding_outcome_item`
        FOREIGN KEY (`encoding_item_id`) REFERENCES `encoding_item` (`id`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
